/**
 * Re-export from agentic-sdk shared module.
 * All consumers import from '@/lib/db/schema' — this shim keeps those imports working.
 */
export {
  projects,
  tasks,
  attempts,
  attemptLogs,
  attemptFiles,
  checkpoints,
  agentFactoryPlugins,
  projectPlugins,
  pluginDependencies,
  pluginDependencyCache,
  shells,
  subagents,
  appSettings,
  type Project,
  type NewProject,
  type Task,
  type NewTask,
  type Attempt,
  type NewAttempt,
  type AttemptLog,
  type NewAttemptLog,
  type Checkpoint,
  type NewCheckpoint,
  type AttemptFile,
  type NewAttemptFile,
  type AgentFactoryPlugin,
  type NewAgentFactoryPlugin,
  type ProjectPlugin,
  type NewProjectPlugin,
  type PluginDependency,
  type NewPluginDependency,
  type PluginDependencyCache,
  type NewPluginDependencyCache,
  type Shell,
  type NewShell,
  type Subagent,
  type NewSubagent,
  type AppSetting,
  type NewAppSetting,
} from '@agentic-sdk/db/database-schema';
